// Balance sweep — runs every non-tutorial mission × strategy × loadout and writes
// a markdown report to tools/balance-report.md.
//
// Usage:
//   pnpm balance              # default: 500 runs per combo (~2 min)
//   pnpm balance -- --runs 5000   # thorough: ~20 min, tight confidence intervals
//   pnpm balance -- --runs 50000  # exhaustive: ~1 hour, ±0.2% accuracy
//
// The report shows clear-rate and per-star rates for every combination so you can
// spot which missions are too hard (clear-rate < 60%) or too easy (> 95%) and
// which stars are impossible (< 5%) or trivial (> 95%).
//
// Claude can then read tools/balance-report.md and suggest tuning changes with
// minimal token usage — no code context needed, just the report.

import { writeFileSync } from 'fs';
import { TICKS_PER_SECOND } from '../src/core/constants';
import { runMission } from '../src/core/replay';
import type { RunPolicies } from '../src/core/replay';
import { buildMissionResult } from '../src/core/result';
import { mulberry32 } from '../src/core/rng';
import type { AbilityOffer, CoreState, LoadoutSnapshot } from '../src/core/types';
import { ALL_ABILITIES, abilityById } from '../src/data/cards';
import { ALL_MISSIONS } from '../src/data/missions';
import { STARTER_LOADOUT } from '../src/data/loadouts';
import { starterKindLoadoutAtLevel, weaponAtKindIndex } from './loadoutPresets';

// ── Loadout presets ──────────────────────────────────────────────────────────
// mid/full read kind index + level from src/data/items.ts's *_KINDS arrays instead
// of hardcoding item ids — see loadoutPresets.ts for why.

const LOADOUTS: Record<string, LoadoutSnapshot> = {
  starter: STARTER_LOADOUT,
  // Weapon a level ahead of the rest — represents prioritizing the starter weapon.
  mid: { ...starterKindLoadoutAtLevel(2), weapon: weaponAtKindIndex(0, 3) },
  // Branched into the second weapon kind — represents having upgraded off the starter.
  full: { ...starterKindLoadoutAtLevel(3), weapon: weaponAtKindIndex(1, 4) },
};

// ── Card strategies ──────────────────────────────────────────────────────────

function randomPolicies(seed: number): RunPolicies {
  const rng = mulberry32(seed ^ 0x5f3759df);
  return { abilityPool: ALL_ABILITIES, pickAbility: () => Math.floor(rng() * 3) };
}

function greedyPolicies(): RunPolicies {
  const priorities: Record<string, number> = { nexus: 0, quantum: 1, aegis: 2, comet: 3 };
  const pickAbility = (_state: CoreState, offer: AbilityOffer): number => {
    let best = 0;
    let bestRank = Number.POSITIVE_INFINITY;
    offer.abilityIds.forEach((cardId, i) => {
      const rank = priorities[abilityById(cardId).company] ?? 9;
      if (rank < bestRank) { bestRank = rank; best = i; }
    });
    return best;
  };
  return { abilityPool: ALL_ABILITIES, pickAbility };
}

// ── Stats accumulator ────────────────────────────────────────────────────────

interface ComboResult {
  missionId: string;
  loadout: string;
  strategy: string;
  runs: number;
  victories: number;
  totalTicks: number;
  starCounts: Map<string, number>;
}

function runCombo(
  missionId: string,
  loadoutKey: string,
  strategyKey: string,
  runs: number,
  baseSeed: number,
): ComboResult {
  const mission = ALL_MISSIONS.find((m) => m.id === missionId);
  if (mission === undefined) throw new Error(`Unknown mission ${missionId}`);
  const loadout = LOADOUTS[loadoutKey];
  if (loadout === undefined) throw new Error(`Unknown loadout ${loadoutKey}`);

  let victories = 0;
  let totalTicks = 0;
  const starCounts = new Map<string, number>();

  for (let i = 0; i < runs; i++) {
    const seed = baseSeed + i;
    const policies = strategyKey === 'greedy' ? greedyPolicies() : randomPolicies(seed);
    const { state } = runMission(mission, loadout, seed, policies);
    const result = buildMissionResult(state);
    if (result.status === 'victory') victories += 1;
    totalTicks += result.durationTicks;
    for (const starId of result.earnedStarIds) {
      starCounts.set(starId, (starCounts.get(starId) ?? 0) + 1);
    }
  }

  return { missionId, loadout: loadoutKey, strategy: strategyKey, runs, victories, totalTicks, starCounts };
}

// ── Report formatting ─────────────────────────────────────────────────────────

function pct(n: number, total: number): string {
  return `${((n / total) * 100).toFixed(1)}%`;
}

function formatReport(results: ComboResult[], missions: typeof ALL_MISSIONS): string {
  const lines: string[] = [
    `# Balance Report`,
    ``,
    `Generated by \`pnpm balance\`. Each cell is clear-rate; starred rows show per-star earn rates.`,
    `**Target**: clear-rate 70–90% on starter/greedy. Stars: no star below 5% or above 95%.`,
    ``,
  ];

  for (const mission of missions) {
    lines.push(`## ${mission.id}: ${mission.name}`);
    lines.push(``);

    const mResults = results.filter((r) => r.missionId === mission.id);

    // Summary table
    lines.push(`| loadout | strategy | clear-rate | avg-duration |`);
    lines.push(`|---------|----------|-----------|--------------|`);
    for (const r of mResults) {
      const avgS = (r.totalTicks / r.runs / TICKS_PER_SECOND).toFixed(1);
      const flag = r.victories / r.runs < 0.6 ? ' ⚠️ TOO HARD' : r.victories / r.runs > 0.95 ? ' 💤 TOO EASY' : '';
      lines.push(`| ${r.loadout} | ${r.strategy} | **${pct(r.victories, r.runs)}**${flag} | ${avgS}s |`);
    }

    lines.push(``);

    // Star detail from the greedy/starter combo (most informative baseline)
    const baseline = mResults.find((r) => r.loadout === 'starter' && r.strategy === 'greedy');
    if (baseline !== undefined && mission.stars.length > 0) {
      lines.push(`**Stars** (starter/greedy):`);
      for (const star of mission.stars) {
        const rate = pct(baseline.starCounts.get(star.id) ?? 0, baseline.runs);
        const flag = (baseline.starCounts.get(star.id) ?? 0) / baseline.runs < 0.05 ? ' ⚠️ UNREACHABLE' :
                     (baseline.starCounts.get(star.id) ?? 0) / baseline.runs > 0.95 ? ' 💤 TRIVIAL' : '';
        lines.push(`- \`${star.id}\` ${rate}${flag}`);
      }
      lines.push(``);
    }
  }

  return lines.join('\n');
}

// ── Main ─────────────────────────────────────────────────────────────────────

function parseRuns(argv: string[]): number {
  const idx = argv.indexOf('--runs');
  if (idx >= 0 && argv[idx + 1] !== undefined) {
    const n = parseInt(argv[idx + 1] ?? '', 10);
    if (Number.isFinite(n) && n > 0) return n;
  }
  return 500;
}

function main(): void {
  const runsPerCombo = parseRuns(process.argv.slice(2));
  const nonTutorial = ALL_MISSIONS.filter((m) => m.forcedLoadout === undefined);
  const loadoutKeys = Object.keys(LOADOUTS);
  const strategyKeys = ['greedy', 'random'];
  const total = nonTutorial.length * loadoutKeys.length * strategyKeys.length;
  let done = 0;

  console.log(`Running ${String(total)} combos × ${String(runsPerCombo)} runs = ${String(total * runsPerCombo)} total simulations…`);

  const results: ComboResult[] = [];
  for (const mission of nonTutorial) {
    for (const loadoutKey of loadoutKeys) {
      for (const strategyKey of strategyKeys) {
        const r = runCombo(mission.id, loadoutKey, strategyKey, runsPerCombo, 1);
        results.push(r);
        done++;
        process.stdout.write(`\r  ${String(done)}/${String(total)} (${mission.id}/${loadoutKey}/${strategyKey})        `);
      }
    }
  }

  console.log('\nDone. Writing report…');
  const report = formatReport(results, nonTutorial);
  // fallow-ignore-next-line unresolved-import
  const outPath = new URL('./balance-report.md', import.meta.url).pathname;
  writeFileSync(outPath, report, 'utf8');
  console.log(`Report written to tools/balance-report.md`);
  console.log(`\nQuick summary:`);
  for (const r of results.filter((r) => r.strategy === 'greedy' && r.loadout === 'starter')) {
    const rate = ((r.victories / r.runs) * 100).toFixed(1);
    const flag = r.victories / r.runs < 0.6 ? '⚠️' : r.victories / r.runs > 0.95 ? '💤' : '✓';
    console.log(`  ${flag} ${r.missionId.padEnd(4)} clear ${rate}%`);
  }
}

main();
