// AUTO-GENERATED by `pnpm tune` (tools/tune-loadouts.ts) — do not hand-edit.
// Re-run `pnpm tune` to regenerate after any items.ts/missions.ts balance change.
// See docs/plans/expert-average-campaign-tuning.md and tools/tune-report.md for the
// full per-system spread/dominant-kind report this table was derived from.

import type { GeneratorKind, MotorKind, ShieldKind, ShipKind } from '../src/data/items';
import type { RearWeaponKind, SideWeaponKind, WeaponKind } from '../src/core/types';

export interface RecommendedKinds {
  weapon: WeaponKind;
  generator: GeneratorKind;
  shield: ShieldKind;
  motor: MotorKind;
  rearWeapon: RearWeaponKind;
  sideWeapon: SideWeaponKind;
  ship: ShipKind;
}

export const RECOMMENDED_KIND_PER_MISSION: Record<string, RecommendedKinds> = {
  m1: { weapon: 'pulse', generator: 'surge', shield: 'wall', motor: 'rush', rearWeapon: 'grenade', sideWeapon: 'focus', ship: 'interceptor' },
  m2: { weapon: 'ion', generator: 'steady', shield: 'wall', motor: 'rush', rearWeapon: 'grenade', sideWeapon: 'focus', ship: 'interceptor' },
  m3: { weapon: 'ion', generator: 'torrent', shield: 'flux', motor: 'rush', rearWeapon: 'grenade', sideWeapon: 'focus', ship: 'interceptor' },
  m3b: { weapon: 'nova', generator: 'torrent', shield: 'wall', motor: 'rush', rearWeapon: 'grenade', sideWeapon: 'focus', ship: 'interceptor' },
  m4: { weapon: 'ion', generator: 'torrent', shield: 'wall', motor: 'rush', rearWeapon: 'grenade', sideWeapon: 'focus', ship: 'interceptor' },
  m5: { weapon: 'scatter', generator: 'torrent', shield: 'wall', motor: 'rush', rearWeapon: 'grenade', sideWeapon: 'focus', ship: 'interceptor' },
  m6: { weapon: 'ion', generator: 'surge', shield: 'wall', motor: 'rush', rearWeapon: 'grenade', sideWeapon: 'focus', ship: 'interceptor' },
};
